#!/bin/bash

FN_SECRET="some-super-long-secret-string"


gcloud alpha functions deploy github-event-handler \
  --entry-point GitHubEventHandler \
  --set-env-vars HOOK_SECRET=$FN_SECRET \
  --memory 128MB \
  --region us-central1 \
  --runtime go111 \
  --trigger-http \
  --retry


gcloud alpha functions add-iam-policy-binding \
  github-event-handler \
  --region us-central1 \
  --member allUsers \
  --role roles/cloudfunctions.invoker