language: go
sudo: false
notifications:
  email: true
go:
 - "1.11.x"

env:
  global:
    - GO111MODULE=on
    - HOOK_SECRET=some-super-long-secret-string

install:
  - go mod tidy

script:
  - go test -v ./...
